version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
  node: circleci/node@4.7
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
